name: ProdigyGui
version: 1.0.42
api-version: 1.13
author: cocoraid
depend: [ProtocolLib]
softdepend: [PlaceholderAPI, Vault]
main: fr.cocoraid.prodigygui.ProdigyGUI
commands:
    prodigygui:
        description: "prodigygui command"

